### ISSUE TITLE
Downloading Answers from Quora Freezes

### ISSUE THREAD

**Issue by BobRedCo** [eloquence/freeyourstuff.cc#67] opened 2017-05-28 20:29 UTC
When trying to download my Quora answers, the counter freezes at some point--once at about 2/3 the way through and once at 3/4 of the way.

In the first case, Quora was showing an "Internet Connection Problem" message. In the second, there was a "Please refresh this page for new updates" message. Are these interfering? Is it possible, that accessing Quora on another computer at the same time is causing the problem? (I was using my iPad.)

I'm also wondering which Quora page your collecting answers from? I looks like it might be the profile page. Might not it work better if you used Your Content? If you could make it work with that, you should also be able to download questions and posts.

P.S. Tom Groves recommended your utility to me. On Quora, I'm Nancy Jacobsen.

**Comment by eloquence** [comment] 2017-05-30 01:08
Hi BobRedCo, thanks for giving it a spin and sorry you're experiencing issues. Quora has been the most troublesome plugin, due to frequent UI changes and throttling employed on Quora's end. I just fixed a couple of issues with the plugin caused by a recent UI change and uploaded a new version.

Chrome auto-updates extensions (you may have to restart and/or wait a bit). As soon as you see the new version, 0.3.15, in the extensions tab (visit chrome://extensions/ ), could you give it another spin and see if the download now successfully completes? If not, I should be able to fetch your answers for you and email them to you.

Regarding your final question, we do use the profile page right now. Posts require some extra work to support, and it's harder to test with the "Content" page since it's unique to each user.

**Comment by BobRedCo** [comment] 2017-05-30 19:29
Hi, Eric -

 

Thanks for getting back to me. I tried it aqain today and it processed
everything much, much faster. However, I kind of reached an impass at the
end.

 

First, when I started the extension, I saw this:

 



 

And it didn't go any further. I was indeed logged into Quora-when am I not?

 

However, when I closed this window and clicked on the extension again, it
worked fine-far far better than before and finished in just a few minutes.
So far, so good!

 

At the end, though, what I was sort of expecting to happen was that I'd be
able to download answers as individual HTML files into a folder (preferably
selected by me) on my computer so I could view and print them offline or
selectively add them to my own website. When I clicked on Download File, all
I got was a 171 byte file called DATA.JSON, which doesn't do anything when I
click on it. Even one single HTML file would be sort okay, although I'd have
to copy stuff out of it to print.

 

I don't really want to post my answers on the Internet, certainly not all my
answers, but I'd be willing to do it temporarily if I could then copy them
back down to my computer and delete them from the Internet.

 

I may just not be understanding how I can do what I want already. Any
suggestions?

 

For what it's worth, I think if you can get it to do what I think I need it
to do, I'd be willing to pay for it and I'd be willing to share it with as
many people as I can on Quora. There's one user in particular that I was
trying to help print answers and I know he'd be interested, but it's also
come up before many times.

 

nj

 

 

 

  _____

**Comment by eloquence** [comment] 2017-05-31 00:02
Hi there,

Thanks for the detailed report. I was able to download all your answers without modifying the extension -- it's a bit hard to debug what went wrong on your end, and the screenshots you attempted to copy in didn't make it through (you can email these to me at eloquence AT gmail DOT com). 

I did notice that some of the answer dates weren't correctly extracted. I'll have to debug a bit to find out what happened there. Otherwise the extract looks fine.

The extension does produce a JSON file that's primarily useful for further post-processing. If you upload it through the site, it also lets you download a CSV and a printable table. The latter might be what you're looking for.

There's no special reason those features (print/CSV) aren't in the extension itself other than that I haven't had time to put them in. :) If you send me an email to the above address, I can send you the extract in a few different formats.

**Comment by eloquence** [comment] 2017-05-31 06:28
I was able to fix the date bug (was due to a UI change in Quora) and have been able to download your answers. I can send you a CSV (which contains the HTML) and PDF if you want.

**Comment by BobRedCo** [comment] 2017-05-31 20:23
Yes, please send me both files so I can see the results. Thanks so much!

 

Does this mean if I click on Download File in the future that I'll get one
or both of them? Will I have a choice?

 

nj

 

  _____

**Comment by eloquence** [comment] 2017-05-31 21:49
Happy to. GitHub doesn't show me your email address, so please email me at `eloquence AT gmail DOT com` and I'll send the files as attachments.

Re: your question, right now the print/CSV exports are only available after publication. I've filed #69 for this; you can subscribe to that issue to get an email notification once that feature is added.

**Comment by eloquence** [comment] 2017-07-19 01:01
Closing this for now since we've had not had reports of frozen downloads since recent changes to the Quora code.

**Closed by eloquence** 2017-07-19 01:01 UTC
