### ISSUE TITLE
Error with Quora plugin

### ISSUE THREAD

**Issue by MssDD** [eloquence/freeyourstuff.cc#82] opened 2017-12-14 16:58 UTC
Error: Attempt to obtain answer timed out after 30 seconds
    at extractAndStoreAnswer (file:///C:/Users/MssDidi/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.3.22_0/src/plugins/quora/index.js:173:19)
    at

**Comment by eloquence** [comment] 2017-12-15 01:12
Quora changed its CSS class names a few days ago, which caused the plugin to fail. This should now be fixed in the plugin.

1) Can you make sure that you're running the latest extension? If you visit chrome://extensions/ , it should show version 0.3.23 . If not, the quickest way to get it is to uninstall and reinstall it.

2) If you're running the latest version, try again. If the problem still occurs, please let me know your Quora profile URL, and I'll try to reproduce it.

**Comment by MssDD** [comment] 2017-12-17 21:28
Thank you so much.

My extension was the latest version.  So, I tried again and was asked to login to Quora, but I was already logged in.  

So, tried once more and like magic, poof! Everything works now.

Hmmm, good ol' Mercury Retrograde... I'm going with that!

Thanks again and thank you for this great extension!

**Closed** 2017-12-17 21:29 UTC

**Comment by eloquence** [comment] 2017-12-17 21:33
Thanks for the update! Yes, there seems to be a new race condition with the login check - will investigate.
