### ISSUE TITLE
Quora extraction does not stop

### ISSUE THREAD

**Issue by maheshcr** [eloquence/freeyourstuff.cc#60] opened 2016-11-17 06:16 UTC
Environment:
Chrome 54.0.2840.71 (64-bit)
Mac OSX El Capitan

Trying to extract my content from Quora profile, while being logged in properly and on my profile page, I found the process did not after 2-3 hours. Noticed in the browser window that the same batch of URLs were popping up continuously. Laptop's fan got all active very frequently, need not be a problem in itself. Had to kill the plugin by un-installing it and closing browser window.

**Comment by eloquence** [comment] 2016-11-17 06:29
Thanks for the report! I've had a couple users reporting similar issues with Quora. If you don't mind letting me know your Quora username, I can try to reproduce it. I should at least be able to get your download for you if I can't.

**Comment by maheshcr** [comment] 2016-11-17 10:50
No issues at all Erik, my profile link is https://www.quora.com/profile/Mahesh-Ramakrishnan
Do let me know if you need any other detail.

**Comment by eloquence** [comment] 2016-11-17 13:21
I was able to download the data -- it took about 15 minutes. Depending on your bandwidth and device, it can take longer, but you may also have encountered a bug that I'm not able to reproduce.

In any case, let me know if you'd like me to send you a copy -- if so, just send me a ping to `eloquence AT gmail DOT com` and I'll send it to you. If you'd like to publish the data under an open license (like the data at https://freeyourstuff.cc/browse ) I can help with that as well.

**Comment by eloquence** [comment] 2017-01-12 11:06
Extraction logic has largely been rewritten for the new answer UI, so closing for the time being.

**Closed by eloquence** 2017-01-12 11:06 UTC
