### ISSUE TITLE
Lack of progress indicators that something is happening.

### ISSUE THREAD

**Issue by sgbotsford** [eloquence/freeyourstuff.cc#79] opened 2017-10-13 01:40 UTC
I'm signed in on Quora
I click on the icon.
I click on Retieve my Answers.
Nothing seems to happen.

Desired behaviour:
* Dialog box comes up and says how many answers are being gotten.
* Icon is replaced with a piechart progress bar.
* request as to where to save them 

OR
* error message that retrieval failed.

**Comment by eloquence** [comment] 2017-10-13 06:56
Hi @sgbotsford , sorry it didn't work for you and thanks for the report. Can you post a link to your Quora profile page, or send it to me at eloquence AT gmail DOT com? That way I can run the extension against that URL and see if I can reproduce the problem.

**Comment by eloquence** [comment] 2018-01-21 01:00
I've just released a major update to the extension (0.4.0) that should be a lot more tolerant of errors on the Quora side, give a progress indicator, and also faster with huge answer sets. Chrome auto-updates extensions, but to be sure, you can uninstall and reinstall the extension from https://freeyourstuff.cc/ - you can find the version you're running by putting chrome://extensions in the address bar.

There may be new errors, too! :-) Please give it a spin and let me know if it works for you now.

**Comment by eloquence** [comment] 2018-01-28 22:33
Closing since there's been no follow up on this from the original reporter.

**Closed by eloquence** 2018-01-28 22:33 UTC
